import java.util.ArrayList;
import java.util.List;

/**
 * This class represents model object in MVC pattern
 *
 * @version 1.0
 * @autor Anna Samonenko
 */
public class Model {

    /**
     * The value generated by random
     */
    private int randomNumber;

    /**
     * The minimum number in the range
     */
    private int minNumber = 0;

    /**
     * The maximum number in the range
     */
    private int maxNumber = 100;

    /**
     * List of user's numbers
     */
    private List<Integer> userNumbers;

    /**
     * Default constructor
     */
    public Model() {
        userNumbers = new ArrayList();
    }

    /**
     * Returns integer value generated by random
     *
     * @return random number
     */
    public int getRandomNumber() {
        return randomNumber;
    }

    /**
     * Sets integer value generated by random
     *
     * @param randomNumber random generated number
     */
    public void setRandomNumber(int randomNumber) {
        this.randomNumber = randomNumber;
    }

    /**
     * Returns integer value which is the minimum number in the range
     *
     * @return the minimum number in the range
     */
    public int getMinNumber() {
        return minNumber;
    }

    /**
     * Sets integer value is the minimum number in the range
     *
     * @param minNumber is the minimum number in the range
     */
    public void setMinNumber(int minNumber) {
        this.minNumber = minNumber;
    }

    /**
     * Returns integer value which is the maximum number in the range
     *
     * @return the maximum number in the range
     */
    public int getMaxNumber() {
        return maxNumber;
    }

    /**
     * Sets integer value is the maximum number in the range
     *
     * @param maxNumber is the maximum number in the range
     */
    public void setMaxNumber(int maxNumber) {
        this.maxNumber = maxNumber;
    }

    /**
     * Returns a list of user's numbers
     *
     * @return list of user's input numbers
     */
    public List<Integer> getUserNumbers() {
        return userNumbers;
    }

    /**
     * Sets a list of user's numbers
     *
     * @param userNumbers list of user's input numbers
     */
    public void setUserNumbers(List<Integer> userNumbers) {
        this.userNumbers = userNumbers;
    }
}
